apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: clustersetups.thesis.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  group: thesis.io
  names:
    kind: clusterSetup
    plural: clustersetups
  connectionSecretKeys:
    - cluster-ca
    - apiserver-endpoint
    - value
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  description: Name of provider
                  type: string

                k8s-version:
                  description: Kubernetes version
                  type: string
                  enum: ["1.20", "1.21", "1.22", "1.23", "1.24"]
                workers-size:
                  description: Desired number of worker nodes in the cluster
                  type: integer
                  default: 2
                workload-type:
                  description: Type of workloads to be run on this cluster (GPU or non-GPU)"
                  type: string
                  enum: ["gpu", "non-gpu"]
                  default: "non-gpu"
                region:
                  description: Geographic location of this Cluster Setup
                  type: string
                  enum: ["eu-central-1", "eu-west-1"]


                vpc-cidrBlock:
                  description: CIDR block for VPC
                  type: string
                  default: "10.19.0.0/16"

                subnets:
                  type: object
                  properties:
                    public:
                      type: object
                      required:
                        - name
                        - cidrBlock
                        - availabilityZone
                      properties:
                        name:
                          type: string
                          description: Name of the subnet
                        cidrBlock:
                          type: string
                          description: CIDR block of the subnet
                        availabilityZone:
                          type: string
                          description: Availability Zone of the subnet
                          enum: [ "a", "b", "c" ]
                    private-1:
                      type: object
                      required:
                        - name
                        - cidrBlock
                        - availabilityZone
                      properties:
                        name:
                          type: string
                          description: Name of the subnet
                        cidrBlock:
                          type: string
                          description: CIDR block of the subnet
                        availabilityZone:
                          type: string
                          description: Availability Zone of the subnet
                          enum: [ "a", "b", "c" ]
                    private-2:
                      type: object
                      required:
                        - name
                        - cidrBlock
                        - availabilityZone
                      properties:
                        name:
                          type: string
                          description: Name of the subnet
                        cidrBlock:
                          type: string
                          description: CIDR block of the subnet
                        availabilityZone:
                          type: string
                          description: Availability Zone of the subnet
                          enum: [ "a", "b", "c" ]
                    default:
                      public:
                        name: "public"
                        cidrBlock: "10.19.0.0/24"
                        availabilityZone: "a"
                      private-1:
                        name: "private-1"
                        cidrBlock: "10.19.1.0/24"
                        availabilityZone: "a"
                      private-2:
                        name: "private-2"
                        cidrBlock: "10.19.2.0/24"
                        availabilityZone: "b"

              required:
                    - region
                    - k8s-version
                    - providerConfigRef