apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: "test"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  rules:
    - name: "add-aws-auth-entry-when-secret-is-created"
      match:
        any:
          - resources:
              kinds:
                - Secret
              namespaces:
                - kube-system
              selector:
                matchLabels:
                  wadtfy.io/secret-type: aws-auth-entry
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: Equals
            value: CREATE
      mutate:
        targets:
          - apiVersion: v1
            kind: ConfigMap
            name: aws-auth
            namespace: kube-system
        patchStrategicMerge:
          metadata:
            labels:
              test: mest